"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.REMOVE_CHOSEN_COMPANY = exports.GET_CHOSEN_COMPANY = exports.REMOVE_ACCEPTED_ORDERS = exports.GET_ACCEPTED_ORDERS = exports.REMOVE_SORTED_ORDERS = exports.GET_SORTED_ORDERS = exports.REMOVE_ORDERS = exports.GET_ORDERS = exports.HIDE_LOADER = exports.SHOW_LOADER = exports.GET_USER_AUTHENTICATION = exports.REMOVE_CURRENT_USER = exports.GET_CURRENT_USER = void 0;
// USER
exports.GET_CURRENT_USER = 'USER/GET_CURRENT_USER';
exports.REMOVE_CURRENT_USER = 'USER/REMOVE_CURRENT_USER';
exports.GET_USER_AUTHENTICATION = 'USER/GET_USER_AUTHENTICATION';
// APP
exports.SHOW_LOADER = 'APP/SHOW_LOADER';
exports.HIDE_LOADER = 'APP/HIDE_LOADER';
// ORDERS
exports.GET_ORDERS = 'ORDERS/GET_ORDERS';
exports.REMOVE_ORDERS = 'ORDERS/REMOVE_ORDERS';
exports.GET_SORTED_ORDERS = 'ORDERS/GET_SORTED_ORDERS';
exports.REMOVE_SORTED_ORDERS = 'ORDERS/REMOVE_SORTED_ORDERS';
exports.GET_ACCEPTED_ORDERS = 'ORDERS/GET_ACCEPTED_ORDERS';
exports.REMOVE_ACCEPTED_ORDERS = 'ORDERS/REMOVE_ACCEPTED_ORDERS';
// COMPANY
exports.GET_CHOSEN_COMPANY = 'COMPANY/GET_CHOSEN_COMPANY';
exports.REMOVE_CHOSEN_COMPANY = 'COMPANY/REMOVE_CHOSEN_COMPANY';
