// USER
export const GET_CURRENT_USER = "USER/GET_CURRENT_USER";
export const REMOVE_CURRENT_USER = "USER/REMOVE_CURRENT_USER";
export const GET_USER_AUTHENTICATION = "USER/GET_USER_AUTHENTICATION";

// APP
export const SHOW_LOADER = "APP/SHOW_LOADER";
export const HIDE_LOADER = "APP/HIDE_LOADER";

// ORDERS
export const GET_ORDERS = "ORDERS/GET_ORDERS";
export const REMOVE_ORDERS = "ORDERS/REMOVE_ORDERS";
export const GET_SORTED_ORDERS = "ORDERS/GET_SORTED_ORDERS";
export const REMOVE_SORTED_ORDERS = "ORDERS/REMOVE_SORTED_ORDERS";
export const GET_ACCEPTED_ORDERS = "ORDERS/GET_ACCEPTED_ORDERS";
export const REMOVE_ACCEPTED_ORDERS = "ORDERS/REMOVE_ACCEPTED_ORDERS";

// COMPANY
export const GET_CHOSEN_COMPANY = "COMPANY/GET_CHOSEN_COMPANY";
export const REMOVE_CHOSEN_COMPANY = "COMPANY/REMOVE_CHOSEN_COMPANY";
